### ISSUE TITLE
Reading encrypted files hanging vim

### ISSUE THREAD

**Issue by vic2r** [applidium/Vim#38] opened 2018-09-23 03:19 UTC
Previously saved files encrpyted with :X cannot be unencrypted.
When I open a file :n test.txt which was encrypted using :X it hangs the app.
Also, when I attempt to encrypt using :X, followed by "Enter Encryption Key:" typing in a key hangs app.  This started happening with iOS 12, with iPhone 7 Plus..., Gvim 8.1.42, and version 7xxx (not sure what I had installed previously)

**Comment by laviallb** [comment] 2018-12-07 09:58
Thanks for the feedback, the issue is fixed in release 1.2.1

**Closed as completed by laviallb** 2018-12-07 09:58 UTC
Labels: bug, requires_attention
